### ISSUE TITLE
How to manage a string like "Hello Marc" ?

### ISSUE THREAD

**Issue by jeremieca** [valscion/babel-plugin-i18n#3]
Hello,

How to properly support variables in strings ? For example, `"Hello $USER"`

I think to do `__("Hello $USER").replace("$USER", "Marc")` but what is your way of doing it ?

Thanks !

**Comment by valscion** [comment]
Hi :)

Variable support is indeed nonexistent. Your way of doing it seems reasonable.

**Comment by jeremieca** [comment]
Ok. Don't you personally use variable when using your library ?

**Comment by valscion** [comment]
I actually don't use this library. It was intended as a replacement for another solution we currently use, which is a webpack plugin, but we never got around to finishing this and using this instead of the webpack plugin.

So here be dragons. I should probably mention that this plugin in unsupported in the README 😅

**Comment by jeremieca** [comment]
Ok. Yes, thanks for mention.
